### ISSUE TITLE
it doesn't work, giving the error Command not found, because the command should be ending on v1 (check_node_cpu_v1)

### ISSUE THREAD

**Issue by sergeyOkuntsev** [dashbase/dashbase-installation#197]
https://github.com/dashbase/dashbase-installation/blob/4c93f4eb9a42e9c7c370f97b7a623ac2f095e377/dashbase-installer.sh#L363

**Comment by rluidash** [comment]
git pull or git clone this repo again..
the dashbase-installer.sh script is updated on June 16 which is 6 days ago when you report this issue.
I guess you are using the old installer script or before the last changes

currently on dashbase-installer.sh script already reflect the "check_node_cpu_v1" function.
https://github.com/dashbase/dashbase-installation/blob/master/dashbase-installer.sh#L362-L388

We split the memory / cpu check requirement between v1 and v2 because the resource requirement and K8s nodes setup is different.
